version: '3.6'
services:
  mysql:
    image: mysql:5.7  #https://hub.docker.com/_/mysql
    environment:
      MYSQL_DATABASE: app # esta base de datos será creada al inicio del contenedor
      MYSQL_USER: alumno #se crea al usuario y se asocia a la base de datos anterior
      MYSQL_PASSWORD: alumno
      MYSQL_ROOT_PASSWORD: alumno
    restart: always
    volumes:
      - volumen1:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d:z

  adminer:
    #indica en la página de login, localhost: mysql
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  volumen1:
